version: "3"

services:

  gateone:
    image: satomic/gateone:http
    ports:
    - "8000:8000"
    hostname: kubectl
    networks:
    - frontend
    volumes:
    - ssh_key:/root/.ssh/

  lab:
    image: satomic/cka_lab
    entrypoint: /opt/entry.bash
    ports:
      - 80:80
    networks:
    - frontend
    volumes:
      - ./entry.bash:/opt/entry.bash:ro
    environment:
      GATEONE_HTTP_SERVER: "115.28.209.81:8000"

networks:
  frontend: {}
volumes:
  ssh_key: {}
