version: '3.6'
services:
  gateone:
    image: satomic/gateone:http
    ports:
    - "8000:8000"
    hostname: kubectl
    networks:
    - frontend
    volumes:
    - ssh_key:/root/.ssh/
  lab:
    image: satomic/cka_lab
    ports:
    - "80:80"
    networks:
    - frontend
networks:
  frontend: {}
volumes:
  ssh_key: {}